server:
  rootPath: /                                 # Jersey path
  applicationContextPath: /                   # Jetty context path
  registerDefaultExceptionMappers: false      # Allows for custom error handling
  applicationConnectors:
    - type: http
      port: 9010
  adminConnectors:
    - type: http
      port: 9011

contactEmail: email@test.com
smtpHost: localhost
smtpUser: username
smtpPass: password

coinHiveKey: asdf
coinHiveRounds: 256